# Basic
title: 杨云飞
subtitle: A NLPer, Dreamer, coder
description: knowledge is power
# 头像里面的标题
avatarTitle: king-yyf
# 头像里面的描述
avatarDesc: NLP / 机器学习
url: "king-yyf.github.io"

# Comment
comment:
    disqus: yyf
    # gitment: xxx // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 5866138940 
    github: king-yyf
    zhihu: king-yyf
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: yfy@pku.edu.cn


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: xxxx  
    host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


